### PR TITLE
Support for IE8

### PR DESCRIPTION
**Pull request by sathishkumar-d**
IE8 doesn't support get and set so on register getting RTE and registration stops midway. 
Enclosed this within try catch to suppress this error and make Registration successful and make it work for events and methods.

Let me know if this can be merged.

### CODE REVIEW

**Comment by johnyanarella** [comment]
As you noted, IE8 does not support `Object.defineProperty()`, and there doesn't appear to be a suitable polyfill to add it.

This means that SWFService cannot proxy ActionScript class instance properties in IE8. So, if you need to support IE8, you'll want to use methods instead of properties or getters/setters in your ActionScript class. 

For example:

``` ActionScript
public function getFoo():String {
    ...
}
public function setFoo( value:String ):void {
    ...
}
```

instead of 

``` ActionScript
public var foo:String;
// or
public function get foo():String {
    ...
}
public function set foo( value:String ):void {
    ...
}
```

Thanks for reporting this issue and providing a pull request.

I think I'd be more inclined to see that section of code guarded with a check for `Object.defineProperty` than a `try..catch`, as that might mask or conflate other types of errors into the condition we really intend to handle here.  Also, `console` is not always defined in older browsers and is only defined in IE8 when the developer tools are open.  (It is not uncommon for projects to define alternatives for `console` methods when absent, so this issue may not have shown up in your project.)

So, when merging this request, I'll probably swap the `try..catch` for a check for whether `Object.defineProperty` is a function, and will change the call to console.log to:

``` coffeescript
console?.log?( 'Warning: SWFService properties and getters/setters are only available for browsers that support ECMAScript 5 properties.' )
```

to provide people with a better clue as to what's going wrong if they are relying on properties and getters/setters.

Thanks for submitting this pull request!

**Comment by ThomasBurleson** [comment]
I realize that  shows [IE8 has only partial support](http://kangax.github.io/es5-compat-table/) for Object.defineProperty. I am worried that wrapping the code in a`try/catch` simply hides the issue... and is perhaps not the best solution to resolve the issue.

**Comment by johnyanarella** [comment]
Ugh.  So IE8 includes a broken implementation of `Object.defineProperty()`?

I see why you were inclined to use `try..catch` now.

**Comment by sathishkumar-d** [comment]
Pardon me for not providing more info earlier.
Yes, have tried inserting an if condition for Object.defineProperty earlier and it still threw below error for IE8.
`TypeError: Object doesn't support this action.` 

There are workarounds mentioned in [MSDN blog](http://blogs.msdn.com/b/ie/archive/2010/09/07/transitioning-existing-code-to-the-es5-getter-setter-apis.aspx) Object.defineProperty.

Have tried using the workarounds suggested for `__defineGetter__` and `__defineGetter__` but it still threw the same error.
`TypeError: Object doesn't support this action.` 

This is because IE8 has defineProperty but only accepts DOM objects

In the [MSDN blog for feature detection](http://blogs.msdn.com/b/ie/archive/2010/04/14/same-markup-writing-cross-browser-code.aspx) check for section _DON'T: Assume Unrelated Features - Real-World Example_ they have used try/catch just that script errors are handled.

PR was just an hot fix for the RTE to allow SWFService to work for events and methods in IE8. 

@johnyanarella 
Your point regarding console not initialized for IE8 without developer tools is correct, please go ahead or let me know for a PR.
My suggestion is to have this in place just to have this working in IE8 for now.

Thanks.

**Comment by sathishkumar-d** [comment]
Had addressed the below issue based on your inputs in the above PR. 
`console is not always defined in older browsers and is only defined in IE8 when the developer tools are open`
Let me know if you need any info. Thanks.

**Comment by johnyanarella** [comment]
Looks good - thanks for making the console.log() change.

**Pull request merged**
